// Spec fields: { formFactorSupport, maxGpuLengthMM (optional) }
export default [
  { id: "manual-case-1", category: "case", name: "Montech AIR 100 ARGB", price: 70, specs: { formFactorSupport: ["mATX", "ITX"] } },
  { id: "manual-case-2", category: "case", name: "Phanteks Eclipse G370A", price: 57, specs: { formFactorSupport: ["ATX", "mATX", "ITX"], maxGpuLengthMM: 400 } },
  { id: "manual-case-3", category: "case", name: "Cooler Master NR200P V3", price: 140, specs: { formFactorSupport: ["ITX"], maxGpuLengthMM: 330 } },
  { id: "manual-case-4", category: "case", name: "Jonsbo TK-0", price: 130, specs: { formFactorSupport: ["ITX"], maxGpuLengthMM: 325 } },
  { id: "manual-case-5", category: "case", name: "Fractal Design Define 7", price: 195, specs: { formFactorSupport: ["ATX", "mATX", "ITX"], maxGpuLengthMM: 440 } },
  { id: "manual-case-6", category: "case", name: "Corsair iCUE 4000X RGB", price: 145, specs: { formFactorSupport: ["ATX", "mATX", "ITX"], maxGpuLengthMM: 400 } },
  { id: "manual-case-7", category: "case", name: "Phanteks XT PRO", price: 68, specs: { formFactorSupport: ["ATX", "mATX", "ITX"], maxGpuLengthMM: 420 } },
  { id: "manual-case-8", category: "case", name: "Cooler Master MasterBox Q300L", price: 37, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-9", category: "case", name: "Aerocool Prism V2 RGB", price: 60, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-10", category: "case", name: "NZXT H5 Elite", price: 70, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-11", category: "case", name: "Fractal Design Focus G Mini", price: 77, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-12", category: "case", name: "BGears b-Voguish RGB", price: 84, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-13", category: "case", name: "Rosewill FBM-X3", price: 90, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-14", category: "case", name: "be quiet! Pure Base 500", price: 100, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-15", category: "case", name: "NZXT H7 Flow (2024)", price: 110, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-16", category: "case", name: "Antec C8 Wood", price: 120, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-17", category: "case", name: "Thermaltake The Tower 250", price: 132, specs: { formFactorSupport: ["ITX"] } },
  { id: "manual-case-18", category: "case", name: "Thermaltake CTE E600", price: 146, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-19", category: "case", name: "Silverstone TJ08B-E", price: 156, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-20", category: "case", name: "Asus TUF Gaming GT501", price: 170, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-21", category: "case", name: "Aerocool Cipher", price: 186, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
  { id: "manual-case-22", category: "case", name: "Antec Performance 1 M", price: 215, specs: { formFactorSupport: ["ITX"] } },
  { id: "manual-case-23", category: "case", name: "Lian Li O11 Dynamic EVO XL", price: 250, specs: { formFactorSupport: ["ATX", "mATX", "ITX"] } },
];