// Spec fields: { supportedSockets }
export default [
  { id: "manual-cooler-1", category: "cooler", name: "ID-COOLING SE-224-XTS", price: 27, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-2", category: "cooler", name: "ARCTIC Liquid Freezer III 240 A-RGB", price: 120, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-3", category: "cooler", name: "Thermalright Frost Commander 140", price: 57, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-4", category: "cooler", name: "ARCTIC Freezer 36", price: 44, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-5", category: "cooler", name: "Cooler Master MASTERLIQUID ML240L RGB V2", price: 87, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-6", category: "cooler", name: "Corsair iCUE LINK H100i RGB", price: 120, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-7", category: "cooler", name: "Noctua NH-L9x65 chromax.black", price: 80, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-8", category: "cooler", name: "ENDORFY Spartan 5", price: 16, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-9", category: "cooler", name: "Thermalright Burst Assassin", price: 22, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-10", category: "cooler", name: "RAIJINTEK LETO RGB", price: 29, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-11", category: "cooler", name: "NZXT T120 RGB", price: 35, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-12", category: "cooler", name: "ID-COOLING FROZN A620 PRO SE ARGB", price: 40, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-13", category: "cooler", name: "Thermalright Frozen Infinity 240 ARGB", price: 47, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-14", category: "cooler", name: "ARCTIC Freezer 8i CO", price: 52, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-15", category: "cooler", name: "ID-COOLING FX240 INF", price: 63, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-16", category: "cooler", name: "MSI MAG CORELIQUID A13", price: 75, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-17", category: "cooler", name: "Cooler Master MasterAIR G200P", price: 85, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-18", category: "cooler", name: "iBuypower AW4", price: 100, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-19", category: "cooler", name: "be quiet! Shadow Rock TF 2", price: 113, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-20", category: "cooler", name: "Gigabyte AORUS WATERFORCE II 360 ICE", price: 130, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-21", category: "cooler", name: "Silverstone VIDA 240 SLIM", price: 146, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-22", category: "cooler", name: "Lian Li Hydroshift LCD 360S", price: 174, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
  { id: "manual-cooler-23", category: "cooler", name: "Lian Li Galahad II Trinity", price: 200, specs: { supportedSockets: ["AM5", "AM4", "LGA1700"] } },
];