export default [
  { id: "manual-cpu-1", category: "cpu", name: "AMD Ryzen 5 9600X", price: 205, specs: { socket: "AM5", ramType: "DDR5", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-2", category: "cpu", name: "AMD Ryzen 7 9700X", price: 306, specs: { socket: "AM5", ramType: "DDR5", tdp: 65, tier: "High-end" } },
  { id: "manual-cpu-3", category: "cpu", name: "Intel Core i5-14400F", price: 126, specs: { socket: "LGA1700", ramType: "DDR5", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-4", category: "cpu", name: "AMD Ryzen 5 8400F", price: 138, specs: { socket: "AM5", ramType: "DDR5", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-5", category: "cpu", name: "AMD Ryzen 7 8700F", price: 240, specs: { socket: "AM5", ramType: "DDR5", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-6", category: "cpu", name: "Intel Core i5-12400F", price: 109, specs: { socket: "LGA1700", ramType: "DDR5", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-7", category: "cpu", name: "Intel Core i3-12100F", price: 79, specs: { socket: "LGA1700", ramType: "DDR5", tdp: 58, tier: "Budget" } },
  { id: "manual-cpu-8", category: "cpu", name: "AMD Ryzen 9 7900", price: 343, specs: { socket: "AM5", ramType: "DDR5", tdp: 65, tier: "High-end" } },
  { id: "manual-cpu-hist-1", category: "cpu", name: "AMD Ryzen 9 5950X", price: 275, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "Enthusiast" } },
  { id: "manual-cpu-hist-2", category: "cpu", name: "AMD Ryzen 9 5900X", price: 255, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "High-end" } },
  { id: "manual-cpu-hist-3", category: "cpu", name: "AMD Ryzen 7 5800X3D", price: 705, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "Gaming" } },
  { id: "manual-cpu-hist-4", category: "cpu", name: "AMD Ryzen 7 5800X", price: 180, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "Gaming" } },
  { id: "manual-cpu-hist-5", category: "cpu", name: "AMD Ryzen 5 5600X", price: 159, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-hist-6", category: "cpu", name: "AMD Ryzen 9 3950X", price: 456, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "Enthusiast" } },
  { id: "manual-cpu-hist-7", category: "cpu", name: "AMD Ryzen 9 3900X", price: 499, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "High-end" } },
  { id: "manual-cpu-hist-8", category: "cpu", name: "AMD Ryzen 7 3800X", price: 270, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "Gaming" } },
  { id: "manual-cpu-hist-9", category: "cpu", name: "AMD Ryzen 7 3700X", price: 143, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-hist-10", category: "cpu", name: "AMD Ryzen 5 3600X", price: 172, specs: { socket: "AM4", ramType: "DDR4", tdp: 95, tier: "Gaming" } },
  { id: "manual-cpu-hist-11", category: "cpu", name: "AMD Ryzen 5 3600", price: 80, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-12", category: "cpu", name: "AMD Ryzen 7 2700X", price: 171, specs: { socket: "AM4", ramType: "DDR4", tdp: 105, tier: "Gaming" } },
  { id: "manual-cpu-hist-13", category: "cpu", name: "AMD Ryzen 7 2700", price: 162, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-hist-14", category: "cpu", name: "AMD Ryzen 5 2600X", price: 115, specs: { socket: "AM4", ramType: "DDR4", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-15", category: "cpu", name: "AMD Ryzen 5 2600", price: 150, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-16", category: "cpu", name: "AMD Ryzen 7 1800X", price: 135, specs: { socket: "AM4", ramType: "DDR4", tdp: 95, tier: "Gaming" } },
  { id: "manual-cpu-hist-17", category: "cpu", name: "AMD Ryzen 7 1700X", price: 429, specs: { socket: "AM4", ramType: "DDR4", tdp: 95, tier: "Gaming" } },
  { id: "manual-cpu-hist-18", category: "cpu", name: "AMD Ryzen 7 1700", price: 165, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Gaming" } },
  { id: "manual-cpu-hist-19", category: "cpu", name: "AMD Ryzen 5 1600X", price: 99, specs: { socket: "AM4", ramType: "DDR4", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-20", category: "cpu", name: "AMD Ryzen 5 1600", price: 99, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-21", category: "cpu", name: "AMD Ryzen 5 1400", price: 80, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-22", category: "cpu", name: "AMD Ryzen 3 1200", price: 70, specs: { socket: "AM4", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-23", category: "cpu", name: "AMD A10-7890K", price: 137, specs: { socket: "FM2+", ramType: "DDR3", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-24", category: "cpu", name: "AMD A10-7850K", price: 140, specs: { socket: "FM2+", ramType: "DDR3", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-25", category: "cpu", name: "AMD A10-7700K", price: 128, specs: { socket: "FM2+", ramType: "DDR3", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-26", category: "cpu", name: "AMD A8-7650K", price: 105, specs: { socket: "FM2+", ramType: "DDR3", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-27", category: "cpu", name: "AMD FX-9590", price: 293, specs: { socket: "AM3+", ramType: "DDR3", tdp: 220, tier: "High-end" } },
  { id: "manual-cpu-hist-28", category: "cpu", name: "AMD FX-9370", price: 217, specs: { socket: "AM3+", ramType: "DDR3", tdp: 220, tier: "High-end" } },
  { id: "manual-cpu-hist-29", category: "cpu", name: "AMD FX-8370", price: 257, specs: { socket: "AM3+", ramType: "DDR3", tdp: 125, tier: "Gaming" } },
  { id: "manual-cpu-hist-30", category: "cpu", name: "AMD FX-8350", price: 192, specs: { socket: "AM3+", ramType: "DDR3", tdp: 125, tier: "Gaming" } },
  { id: "manual-cpu-hist-31", category: "cpu", name: "AMD FX-8320", price: 107, specs: { socket: "AM3+", ramType: "DDR3", tdp: 125, tier: "Gaming" } },
  { id: "manual-cpu-hist-32", category: "cpu", name: "AMD FX-6300", price: 63, specs: { socket: "AM3+", ramType: "DDR3", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-33", category: "cpu", name: "AMD FX-4300", price: 122, specs: { socket: "AM3+", ramType: "DDR3", tdp: 95, tier: "Budget" } },
  { id: "manual-cpu-hist-34", category: "cpu", name: "Intel Core i9-10900K", price: 549, specs: { socket: "LGA1200", ramType: "DDR4", tdp: 125, tier: "Enthusiast" } },
  { id: "manual-cpu-hist-35", category: "cpu", name: "Intel Core i7-10700K", price: 349, specs: { socket: "LGA1200", ramType: "DDR4", tdp: 125, tier: "High-end" } },
  { id: "manual-cpu-hist-36", category: "cpu", name: "Intel Core i5-10600K", price: 175, specs: { socket: "LGA1200", ramType: "DDR4", tdp: 125, tier: "Gaming" } },
  { id: "manual-cpu-hist-37", category: "cpu", name: "Intel Core i9-11900K", price: 449, specs: { socket: "LGA1200", ramType: "DDR4", tdp: 125, tier: "Enthusiast" } },
  { id: "manual-cpu-hist-38", category: "cpu", name: "Intel Core i5-11600K", price: 170, specs: { socket: "LGA1200", ramType: "DDR4", tdp: 125, tier: "Gaming" } },
  { id: "manual-cpu-hist-39", category: "cpu", name: "Intel Core i9-9900K", price: 399, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 95, tier: "Enthusiast" } },
  { id: "manual-cpu-hist-40", category: "cpu", name: "Intel Core i7-9700K", price: 239, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 95, tier: "High-end" } },
  { id: "manual-cpu-hist-41", category: "cpu", name: "Intel Core i5-9600K", price: 166, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 95, tier: "Gaming" } },
  { id: "manual-cpu-hist-42", category: "cpu", name: "Intel Core i7-8700K", price: 179, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 95, tier: "High-end" } },
  { id: "manual-cpu-hist-43", category: "cpu", name: "Intel Core i5-8600K", price: 327, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 95, tier: "Gaming" } },
  { id: "manual-cpu-hist-44", category: "cpu", name: "Intel Core i5-8400", price: 179, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-45", category: "cpu", name: "Intel Core i3-8100", price: 61, specs: { socket: "LGA1151v2", ramType: "DDR4", tdp: 65, tier: "Budget" } },
  { id: "manual-cpu-hist-46", category: "cpu", name: "Intel Core i7-7700K", price: 152, specs: { socket: "LGA1151", ramType: "DDR4", tdp: 91, tier: "High-end" } },
  { id: "manual-cpu-hist-47", category: "cpu", name: "Intel Core i5-7600K", price: 183, specs: { socket: "LGA1151", ramType: "DDR4", tdp: 91, tier: "Gaming" } },
  { id: "manual-cpu-hist-48", category: "cpu", name: "Intel Core i3-7100", price: 37, specs: { socket: "LGA1151", ramType: "DDR4", tdp: 51, tier: "Budget" } },
  { id: "manual-cpu-hist-49", category: "cpu", name: "Intel Core i7-6700K", price: 229, specs: { socket: "LGA1151", ramType: "DDR4", tdp: 91, tier: "High-end" } },
  { id: "manual-cpu-hist-50", category: "cpu", name: "Intel Core i5-6600K", price: 90, specs: { socket: "LGA1151", ramType: "DDR4", tdp: 91, tier: "Gaming" } },
  { id: "manual-cpu-hist-51", category: "cpu", name: "Intel Core i3-6100", price: 30, specs: { socket: "LGA1151", ramType: "DDR4", tdp: 51, tier: "Budget" } },
  { id: "manual-cpu-hist-52", category: "cpu", name: "Intel Core i7-4790K", price: 131, specs: { socket: "LGA1150", ramType: "DDR3", tdp: 88, tier: "High-end" } },
  { id: "manual-cpu-hist-53", category: "cpu", name: "Intel Core i5-4690K", price: 54, specs: { socket: "LGA1150", ramType: "DDR3", tdp: 88, tier: "Gaming" } },
  { id: "manual-cpu-hist-54", category: "cpu", name: "Intel Core i7-4770K", price: 99, specs: { socket: "LGA1150", ramType: "DDR3", tdp: 84, tier: "High-end" } },
  { id: "manual-cpu-hist-55", category: "cpu", name: "Intel Core i5-4670K", price: 106, specs: { socket: "LGA1150", ramType: "DDR3", tdp: 84, tier: "Gaming" } },
  { id: "manual-cpu-hist-56", category: "cpu", name: "Intel Core i3-4130", price: 41, specs: { socket: "LGA1150", ramType: "DDR3", tdp: 54, tier: "Budget" } },
  { id: "manual-cpu-hist-57", category: "cpu", name: "Intel Core i7-3770K", price: 332, specs: { socket: "LGA1155", ramType: "DDR3", tdp: 77, tier: "High-end" } },
  { id: "manual-cpu-hist-58", category: "cpu", name: "Intel Core i5-3570K", price: 129, specs: { socket: "LGA1155", ramType: "DDR3", tdp: 77, tier: "Gaming" } },
  { id: "manual-cpu-hist-59", category: "cpu", name: "Intel Core i3-3220", price: 125, specs: { socket: "LGA1155", ramType: "DDR3", tdp: 55, tier: "Budget" } },
  { id: "manual-cpu-hist-60", category: "cpu", name: "Intel Core i7-2700K", price: 196, specs: { socket: "LGA1155", ramType: "DDR3", tdp: 95, tier: "High-end" } },
  { id: "manual-cpu-hist-61", category: "cpu", name: "Intel Core i5-2500K", price: 100, specs: { socket: "LGA1155", ramType: "DDR3", tdp: 95, tier: "Gaming" } },
];