// Spec fields: { socket, ramType, formFactor }
export default [
  { id: "manual-mobo-1", category: "motherboard", name: "ASRock B850M-X WiFi", price: 125, specs: { socket: "AM5", ramType: "DDR5", formFactor: "mATX" } },
  { id: "manual-mobo-2", category: "motherboard", name: "Gigabyte B760 DS3H AX", price: 160, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-3", category: "motherboard", name: "ASRock B450M Steel Legend", price: 93, specs: { socket: "AM4", ramType: "DDR4", formFactor: "mATX" } },
  { id: "manual-mobo-4", category: "motherboard", name: "Asus ROG STRIX X670E-F GAMING WIFI", price: 418, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-5", category: "motherboard", name: "Gigabyte Z690 AORUS ELITE DDR4", price: 303, specs: { socket: "LGA1700", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-6", category: "motherboard", name: "ASRock B650M-H/M.2+", price: 100, specs: { socket: "AM5", ramType: "DDR5", formFactor: "mATX" } },
  { id: "manual-mobo-7", category: "motherboard", name: "Gigabyte B850 AORUS ELITE WIFI7", price: 233, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-8", category: "motherboard", name: "ASRock A520M-HDV", price: 63, specs: { socket: "AM4", ramType: "DDR4", formFactor: "mATX" } },
  { id: "manual-mobo-9", category: "motherboard", name: "MSI PRO B760M-P DDR4", price: 100, specs: { socket: "LGA1700", ramType: "DDR4", formFactor: "mATX" } },
  { id: "manual-mobo-10", category: "motherboard", name: "Asus TUF GAMING A520M-PLUS WIFI", price: 110, specs: { socket: "AM4", ramType: "DDR4", formFactor: "mATX" } },
  { id: "manual-mobo-11", category: "motherboard", name: "ASRock B450 Pro4", price: 122, specs: { socket: "AM4", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-12", category: "motherboard", name: "Asus PRIME B760M-A AX", price: 132, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "mATX" } },
  { id: "manual-mobo-13", category: "motherboard", name: "MSI PRO B650M-A WIFI", price: 146, specs: { socket: "AM5", ramType: "DDR5", formFactor: "mATX" } },
  { id: "manual-mobo-14", category: "motherboard", name: "MSI PRO H610M-E", price: 151, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "mATX" } },
  { id: "manual-mobo-15", category: "motherboard", name: "MSI PRO B840-P WIFI", price: 160, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-16", category: "motherboard", name: "Gigabyte B650M D3HP", price: 169, specs: { socket: "AM5", ramType: "DDR5", formFactor: "mATX" } },
  { id: "manual-mobo-17", category: "motherboard", name: "ASRock H670 Steel Legend", price: 173, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-18", category: "motherboard", name: "Biostar B760A-SILVER", price: 180, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-19", category: "motherboard", name: "MSI PRO B760-P WIFI", price: 190, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-20", category: "motherboard", name: "ASRock B850 Riptide WiFi", price: 200, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-21", category: "motherboard", name: "ASRock B550 Steel Legend", price: 205, specs: { socket: "AM4", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-22", category: "motherboard", name: "Asus ROG STRIX B650E-I GAMING WIFI", price: 220, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ITX" } },
  { id: "manual-mobo-23", category: "motherboard", name: "Gigabyte B650 AERO G", price: 230, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-24", category: "motherboard", name: "Asus ProArt B550-CREATOR", price: 240, specs: { socket: "AM4", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-25", category: "motherboard", name: "Gigabyte Z790 AORUS ELITE DDR4", price: 256, specs: { socket: "LGA1700", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-26", category: "motherboard", name: "MSI MAG X870 TOMAHAWK WIFI", price: 270, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-27", category: "motherboard", name: "MSI MPG B650I EDGE WIFI", price: 290, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ITX" } },
  { id: "manual-mobo-28", category: "motherboard", name: "Asus ROG STRIX Z690-A GAMING WIFI D4", price: 310, specs: { socket: "LGA1700", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-29", category: "motherboard", name: "Gigabyte X870E AORUS PRO", price: 350, specs: { socket: "AM5", ramType: "DDR5", formFactor: "ATX" } },
  { id: "manual-mobo-30", category: "motherboard", name: "MSI MAG Z690 TOMAHAWK WIFI DDR4", price: 399, specs: { socket: "LGA1700", ramType: "DDR4", formFactor: "ATX" } },
  { id: "manual-mobo-31", category: "motherboard", name: "ASRock Z790I Lightning WiFi", price: 443, specs: { socket: "LGA1700", ramType: "DDR5", formFactor: "ITX" } },
];