// Spec fields: { wattage, efficiency }
export default [
  { id: "manual-psu-1", category: "psu", name: "Thermaltake Smart 600W", price: 45, specs: { wattage: 600, efficiency: "bronze" } },
  { id: "manual-psu-2", category: "psu", name: "be quiet! Pure Power 12 M 750W", price: 99, specs: { wattage: 750, efficiency: "gold" } },
  { id: "manual-psu-3", category: "psu", name: "Corsair SF750 (2024) 750W SFX", price: 180, specs: { wattage: 750, efficiency: "platinum" } },
  { id: "manual-psu-4", category: "psu", name: "EVGA 650 GQ", price: 146, specs: { wattage: 650, efficiency: "gold" } },
  { id: "manual-psu-5", category: "psu", name: "SeaSonic Focus GX V4 750W", price: 130, specs: { wattage: 750, efficiency: "gold" } },
  { id: "manual-psu-6", category: "psu", name: "Cooler Master MWE White V2 650W", price: 126, specs: { wattage: 650, efficiency: "bronze" } },
  { id: "manual-psu-7", category: "psu", name: "Silverstone SX500-G SFX 500W", price: 113, specs: { wattage: 500, efficiency: "gold" } },
  { id: "manual-psu-8", category: "psu", name: "CoolMax I-500", price: 26, specs: { wattage: 500, efficiency: null } },
  { id: "manual-psu-9", category: "psu", name: "Thermaltake Smart BX1 650", price: 63, specs: { wattage: 650, efficiency: "bronze" } },
  { id: "manual-psu-10", category: "psu", name: "Apevia ATX-PR850W PCIE5.0", price: 75, specs: { wattage: 850, efficiency: "gold" } },
  { id: "manual-psu-11", category: "psu", name: "Vetroo 50315153277247", price: 90, specs: { wattage: 850, efficiency: "gold" } },
  { id: "manual-psu-12", category: "psu", name: "Cooler Master MWE Gold 750 V3", price: 100, specs: { wattage: 750, efficiency: "gold" } },
  { id: "manual-psu-13", category: "psu", name: "MSI MAG A750GL PCIE5", price: 110, specs: { wattage: 750, efficiency: "gold" } },
  { id: "manual-psu-14", category: "psu", name: "SeaSonic SSP-300SUG", price: 119, specs: { wattage: 300, efficiency: "gold" } },
  { id: "manual-psu-15", category: "psu", name: "SeaSonic SS-600ES", price: 129, specs: { wattage: 600, efficiency: "bronze" } },
  { id: "manual-psu-16", category: "psu", name: "SeaSonic Platinum", price: 135, specs: { wattage: 600, efficiency: "bronze" } },
  { id: "manual-psu-17", category: "psu", name: "Gigabyte UD1000GM PG5 (rev. 2.0)", price: 148, specs: { wattage: 1000, efficiency: "gold" } },
  { id: "manual-psu-18", category: "psu", name: "be quiet! Pure Power 13 M", price: 160, specs: { wattage: 1000, efficiency: "gold" } },
  { id: "manual-psu-19", category: "psu", name: "Athena Power AP-MFATX50P8", price: 170, specs: { wattage: 500, efficiency: "silver" } },
  { id: "manual-psu-20", category: "psu", name: "Corsair RM750x (2018)", price: 184, specs: { wattage: 750, efficiency: "gold" } },
  { id: "manual-psu-21", category: "psu", name: "Corsair RM1200e", price: 200, specs: { wattage: 1200, efficiency: "gold" } },
  { id: "manual-psu-22", category: "psu", name: "Asus TUF Gaming 1200G", price: 218, specs: { wattage: 1200, efficiency: "gold" } },
  { id: "manual-psu-23", category: "psu", name: "Asus ROG STRIX 1200P Gaming", price: 255, specs: { wattage: 1200, efficiency: "platinum" } },
];