// Spec fields: { type, capacity }
export default [
  { id: "manual-ram-1", category: "ram", name: "Corsair Vengeance 16GB DDR5-5200", price: 65, specs: { type: "DDR5", capacity: "16GB" } },
  { id: "manual-ram-2", category: "ram", name: "TEAMGROUP T-Force Vulcan Z 32GB DDR4-3200", price: 66, specs: { type: "DDR4", capacity: "32GB" } },
  { id: "manual-ram-3", category: "ram", name: "G.Skill Ripjaws S5 32GB DDR5-6000", price: 110, specs: { type: "DDR5", capacity: "32GB" } },
  { id: "manual-ram-4", category: "ram", name: "Crucial Pro Overclocking 32GB DDR5-6000", price: 85, specs: { type: "DDR5", capacity: "32GB" } },
  { id: "manual-ram-5", category: "ram", name: "Corsair Dominator Titanium 32GB DDR5-6000", price: 181, specs: { type: "DDR5", capacity: "32GB" } },
  { id: "manual-ram-6", category: "ram", name: "TEAMGROUP T-Create Expert 32GB DDR4-3200", price: 63, specs: { type: "DDR4", capacity: "32GB" } },
  { id: "manual-ram-7", category: "ram", name: "Kingston Fury Renegade RGB 32GB DDR5-6400", price: 169, specs: { type: "DDR5", capacity: "32GB" } },
  { id: "manual-ram-8", category: "ram", name: "Patriot Signature Line 4 GB", price: 16, specs: { type: "DDR4", capacity: "4GB" } },
  { id: "manual-ram-9", category: "ram", name: "Silicon Power SP008GBLFU266B02 8 GB", price: 23, specs: { type: "DDR4", capacity: "8GB" } },
  { id: "manual-ram-10", category: "ram", name: "Crucial CT8G4RFS424A 8 GB", price: 29, specs: { type: "DDR4", capacity: "8GB" } },
  { id: "manual-ram-11", category: "ram", name: "Crucial CT2K4G4SFS624A 8 GB", price: 35, specs: { type: "DDR4", capacity: "8GB" } },
  { id: "manual-ram-12", category: "ram", name: "Kingston Fury Beast RGB Special Edition 8 GB", price: 40, specs: { type: "DDR4", capacity: "8GB" } },
  { id: "manual-ram-13", category: "ram", name: "Kingston KTD-PE421/16G 16 GB", price: 44, specs: { type: "DDR4", capacity: "16GB" } },
  { id: "manual-ram-14", category: "ram", name: "Crucial CT16G4DFD832A 16 GB", price: 55, specs: { type: "DDR4", capacity: "16GB" } },
  { id: "manual-ram-15", category: "ram", name: "Mushkin MES4S266KF8GX2 16 GB", price: 62, specs: { type: "DDR4", capacity: "16GB" } },
  { id: "manual-ram-16", category: "ram", name: "Patriot Viper Steel 32 GB", price: 72, specs: { type: "DDR4", capacity: "32GB" } },
  { id: "manual-ram-17", category: "ram", name: "TEAMGROUP T-Force Vulcan Z 16 GB", price: 79, specs: { type: "DDR4", capacity: "16GB" } },
  { id: "manual-ram-18", category: "ram", name: "Crucial CT16G4WFD8266 16 GB", price: 88, specs: { type: "DDR4", capacity: "16GB" } },
  { id: "manual-ram-19", category: "ram", name: "Crucial CT32G4SFD8266 32 GB", price: 99, specs: { type: "DDR4", capacity: "32GB" } },
  { id: "manual-ram-20", category: "ram", name: "G.Skill Trident Z5 Neo RGB 48 GB", price: 110, specs: { type: "DDR5", capacity: "48GB" } },
  { id: "manual-ram-21", category: "ram", name: "G.Skill Trident Z 32 GB", price: 129, specs: { type: "DDR4", capacity: "32GB" } },
  { id: "manual-ram-22", category: "ram", name: "Thermaltake TOUGHRAM XG RGB 16 GB", price: 144, specs: { type: "DDR4", capacity: "16GB" } },
  { id: "manual-ram-23", category: "ram", name: "TEAMGROUP Elite 64 GB", price: 160, specs: { type: "DDR4", capacity: "64GB" } },
  { id: "manual-ram-24", category: "ram", name: "Patriot Viper Elite 5 RGB 64 GB", price: 180, specs: { type: "DDR5", capacity: "64GB" } },
  { id: "manual-ram-25", category: "ram", name: "G.Skill F5-5600J2834F32GX2-TZ5RK 64 GB", price: 200, specs: { type: "DDR5", capacity: "64GB" } },
  { id: "manual-ram-26", category: "ram", name: "ADATA XPG LANCER RGB 48 GB", price: 224, specs: { type: "DDR5", capacity: "48GB" } },
  { id: "manual-ram-27", category: "ram", name: "Patriot Signature Line 64 GB", price: 255, specs: { type: "DDR4", capacity: "64GB" } },
];