// Spec fields: { capacity, type }
export default [
  { id: "manual-storage-1", category: "storage", name: "Crucial P5 Plus 2TB NVMe SSD", price: 229, specs: { capacity: "2TB", type: "SSD" } },
  { id: "manual-storage-2", category: "storage", name: "Toshiba X300 4TB HDD", price: 149, specs: { capacity: "4TB", type: "HDD" } },
  { id: "manual-storage-3", category: "storage", name: "Samsung 970 Evo Plus 1TB", price: 134, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-4", category: "storage", name: "Western Digital WD Blue SN5000 1TB", price: 60, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-5", category: "storage", name: "Seagate FireCuda 530 1TB", price: 140, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-6", category: "storage", name: "Kingston Fury Renegade 1TB", price: 118, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-7", category: "storage", name: "Toshiba P300 2TB HDD", price: 85, specs: { capacity: "2TB", type: "HDD" } },
  { id: "manual-storage-8", category: "storage", name: "Toshiba MQ01ABD050", price: 18, specs: { capacity: "500GB", type: "HDD" } },
  { id: "manual-storage-9", category: "storage", name: "TEAMGROUP QX", price: 33, specs: { capacity: "512GB", type: "SSD" } },
  { id: "manual-storage-10", category: "storage", name: "Western Digital WD Blue SN5000", price: 45, specs: { capacity: "500GB", type: "SSD" } },
  { id: "manual-storage-11", category: "storage", name: "Western Digital Red SN700", price: 53, specs: { capacity: "250GB", type: "SSD" } },
  { id: "manual-storage-12", category: "storage", name: "Lexar NQ710", price: 62, specs: { capacity: "500GB", type: "SSD" } },
  { id: "manual-storage-13", category: "storage", name: "Crucial CT1000E100SSD8", price: 72, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-14", category: "storage", name: "Crucial P1", price: 85, specs: { capacity: "500GB", type: "SSD" } },
  { id: "manual-storage-15", category: "storage", name: "ADATA SU800", price: 96, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-16", category: "storage", name: "GameStop 23VG-GSPL-GameStop NVMe SSD-Heatsink-1TB", price: 110, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-17", category: "storage", name: "Western Digital Black SN850", price: 127, specs: { capacity: "500GB", type: "SSD" } },
  { id: "manual-storage-18", category: "storage", name: "Seagate Lightsaber Collection FireCuda", price: 140, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-19", category: "storage", name: "Hitachi 0B36040", price: 153, specs: { capacity: "4TB", type: "HDD" } },
  { id: "manual-storage-20", category: "storage", name: "SanDisk Z410", price: 171, specs: { capacity: "480GB", type: "SSD" } },
  { id: "manual-storage-21", category: "storage", name: "Micron 1100", price: 200, specs: { capacity: "1TB", type: "SSD" } },
  { id: "manual-storage-22", category: "storage", name: "Samsung 980 Pro w/Heatsink", price: 235, specs: { capacity: "2TB", type: "SSD" } },
  { id: "manual-storage-23", category: "storage", name: "Lenovo 5300", price: 259, specs: { capacity: "240GB", type: "SSD" } },
  { id: "manual-storage-24", category: "storage", name: "Mushkin Vortex Redline", price: 309, specs: { capacity: "4TB", type: "SSD" } },
  { id: "manual-storage-25", category: "storage", name: "Corsair CSSD-F4000GBMP600PHX", price: 380, specs: { capacity: "4TB", type: "SSD" } },
];